[build]
  command = "npm install && npm install --prefix netlify/functions && npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"