[build]
  command = "npm install"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  included_files = ["netlify/functions/completed_orders.json"]
  node_bundler = "esbuild"

[dev]
  publish = "."
  port = 8888
  framework = "#static"