[build]
  command = "npm install" # Or any other build command you have
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  included_files = ["netlify/functions/completed_orders.json"]

[functions]
  node_bundler = "esbuild"