[build]
  command = "npm install && npm install --prefix netlify/functions && npm run build"
  publish = "public"
  functions = "netlify/functions"
  node_version = "16"
  functions_node_modules = true

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"